spring:
  application:
    name: consumer-demo

  # config kafka consumer
  kafka:
    consumer:
      bootstrap-servers: localhost:29092
      group-id: consumer-demo-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring:
          json:
            value:
              default:
                type: co.istad.kh.consumer_demo.listener.OrderEvent

            trusted:
              packages: co.istad.kh.consumer_demo.listener
            use:
              type:
                headers: false
      
